export const typeColors: Record<string, string> = {
    normal: "bg-gray-200",
    fire: "bg-orange-500",
    water: "bg-blue-300",
    electric: "bg-yellow-400",
    grass :"bg-green-300",
    ice:"bg-cyan-300",
    fighting:"bg-ambar-800",
    poison:"bg-purple-600",
    ground:"bg-brown-300",
    flying:"bg-cyan-100",
    psychic:"bg-purple-300",
    bug:"bg-green-200",
    rock:"bg-brown-800",
    ghost:"bg-gray-800",
    dragon:"bg-purple-800",
    dark:"bg-black",
    steel:"bg-gray-100",
    fairy:"bg-pink-200",
}